name: Build, Test, and Package .NET Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION_FILE: ${{ github.workspace }}/src/apps/AndGPT.sln
      ARTIFACTS_BASE_DIR: ${{ github.workspace }}/Artifacts
      ARTIFACTS_BIN_DIR: ${{ github.workspace }}/Artifacts/bin
      OUTPUT_DIR: ${{ github.workspace }}/output
      DEPENDENCY_PACKAGES_DIR: ${{ github.workspace }}/Artifacts/DependencyPackages
      MSIX_OUTPUT_DIR: ${{ github.workspace }}/Artifacts/MSIX
      BUILD_ARTIFACTS_PATH: ${{ env.ARTIFACTS_BIN_DIR }}/${{ matrix.platform }}/${{ matrix.configuration }}/apps/HeyGPT
      PDB_OUTPUT_DIR: ${{ env.ARTIFACTS_BASE_DIR }}/PDBs
      PFX_BASE64: ${{ secrets.BASE64_ENCODED_PFX }}
      PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}

    strategy:
      matrix:
        platform: [x64, arm64]
        configuration: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Create artifacts directories
      run: |
        mkdir -p ${{ env.ARTIFACTS_BIN_DIR }}
        mkdir -p ${{ env.DEPENDENCY_PACKAGES_DIR }}
        mkdir -p ${{ env.MSIX_OUTPUT_DIR }}
        mkdir -p ${{ env.PDB_OUTPUT_DIR }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }} --packages ${{ env.DEPENDENCY_PACKAGES_DIR }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-restore -p:Deterministic=true -p:ContinuousIntegrationBuild=true -p:Platform=${{ matrix.platform }}

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal -p:Platform=${{ matrix.platform }}

    - name: Decode PFX file
      run: echo ${{ env.PFX_BASE64 }} | base64 -d > signingkey.pfx

    - name: Create MSIX package
      env:
        APPX_BUNDLE: "Always"
        PACKAGE_BUILD_MODE: "StoreUpload"
        DETERMINISTIC: "true"
        CI_BUILD: "true"
        MSIX_OUTPUT_DIR: ${{ env.MSIX_OUTPUT_DIR }}
      run: msbuild ${{ env.SOLUTION_FILE }} /t:Restore,Rebuild /p:Configuration=${{ matrix.configuration }} /p:AppxBundle=${{ env.APPX_BUNDLE }} /p:UapAppxPackageBuildMode=${{ env.PACKAGE_BUILD_MODE }} /p:Deterministic=${{ env.DETERMINISTIC }} /p:ContinuousIntegrationBuild=${{ env.CI_BUILD }} /p:Platform=${{ matrix.platform }} /p:PackageCertificateKeyFile=signingkey.pfx /p:PackageCertificatePassword=${{ env.PFX_PASSWORD }} /p:PackageOutputPath=${{ env.MSIX_OUTPUT_DIR }}

    - name: Delete PFX file
      run: del signingkey.pfx

    - name: Gather debug files
      run: |
        find ${{ github.workspace }} -name "*.pdb" -exec cp {} ${{ env.PDB_OUTPUT_DIR }} \;

    - name: Zip debug files
      run: |
        cd ${{ env.PDB_OUTPUT_DIR }}
        tar -czvf ${{ env.PDB_OUTPUT_DIR }}/debug_files.tar.gz ./*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HeyGPT-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ${{ env.BUILD_ARTIFACTS_PATH }}/**/*
        retention-days: 5

    - name: Upload MSIX packages
      uses: actions/upload-artifact@v2
      with:
        name: HeyGPT-MSIX-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ${{ env.MSIX_OUTPUT_DIR }}/**/*
        retention-days: 5

    - name: Upload debug files
      uses: actions/upload-artifact@v2
      with:
        name: HeyGPT-Debug-Files-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ${{ env.PDB_OUTPUT_DIR }}/debug_files.tar.gz
        retention-days: 5